matrix:
  include:
    - os: linux
      language: python
      cache: pip
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: NEPHTYS_CMAKE_DEBUG_GCC_8=ON

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ] && [ "${NEPHTYS_CMAKE_DEBUG_GCC_8}" == "ON" ]; then
      CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      pip install conan
      conan profile new default --detect
      conan profile update settings.compiler.libcxx=libstdc++11 default  # Sets libcxx to C++11 ABI
      conan profile update settings.compiler.version=8
      conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      conan remote add skypjack https://api.bintray.com/conan/skypjack/conan
    fi

  - cd -

script:
  - |
    if [[ "${NEPHTYS_CMAKE_DEBUG_GCC_8}" == ON ]]; then
      mkdir cmake-build-debug
      cd cmake-build-debug
      conan install ../
      ${DEPS_DIR}/cmake/bin/cmake -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_C_COMPILER=gcc-8 ../
      make VERBOSE=1 -j2
    fi