version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      GENERATOR: Visual Studio 15 2017 Win64
      BUILD_TYPE: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      GENERATOR: Visual Studio 15 2017 Win64
      BUILD_TYPE: Release

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmake --version
  - msbuild /version

install:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user # Create the conan data directory
  - conan --version
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add skypjack https://api.bintray.com/conan/skypjack/conan
  - conan remote add conan-doom_strong_types https://api.bintray.com/conan/milerius/doom_strong_types

before_build:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - conan install ../.conan/windows -s build_type=%BUILD_TYPE%
  - cmake ../ -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"

build_script:
  - cmake --build . --config %BUILD_TYPE% -- /verbosity:minimal /maxcpucount:3
  - cd bin && ls
  - ps: |
      $filePattern = '*-test.exe'
      foreach ($file in get-ChildItem $filePattern)
      {
        $var = $file.name
        ./$var --reporters=xml --out="$var-result.xml" -s
      }
  #- nephtys-sfml-graphics-test.exe --reporters=xml --out=nephtys-sfml-graphics-result.xml -s
  #- nephtys-client-test.exe --reporters=xml --out=nephtys-client-result.xml -s
  #- nephtys-common-test.exe --reporters=xml --out=nephtys-common-result.xml -s

on_failure:
  - curl -s https://report.ci/annotate.py | python - --tool msvc --input build.log

on_finish:
  # Framework with autodetection
  - ps: |
      $string = "$env:GENERATOR-$env:BUILD_TYPE"
      echo $string
      $string = $string -replace ' ', '-'
      echo $string
      Invoke-WebRequest -Uri https://report.ci/upload.py -OutFile upload.py
      python upload.py -n "Doctest [appveyor $($string)]"