version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      GENERATOR: Visual Studio 15 2017 Win64

init:
  - cmake --version
  - msbuild /version

install:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user # Create the conan data directory
  - conan --version
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add skypjack https://api.bintray.com/conan/skypjack/conan
  - conan remote add conan-doom_strong_types https://api.bintray.com/conan/milerius/doom_strong_types

before_build:
  - git submodule -q update --init
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - conan install ../
  - cmake ../ -G "%GENERATOR%" -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"

build_script:
  - cmake --build . --config Debug